package com.vetery.util;

public class EmailBody {

	public static final String emailBody = "<!DOCTYPE html>\r\n"
			+ "<html lang=\"es\">\r\n"
			+ "<head>\r\n"
			+ "  <meta charset=\"UTF-8\" />\r\n"
			+ "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />\r\n"
			+ "  <title>Novedades Sanvent</title>\r\n"
			+ "  <style>\r\n"
			+ "    body {\r\n"
			+ "      margin: 0;\r\n"
			+ "      padding: 0;\r\n"
			+ "      font-family: Arial, sans-serif;\r\n"
			+ "      background-color: #f4f4f4;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    .email-container {\r\n"
			+ "      max-width: 600px;\r\n"
			+ "      margin: 0 auto;\r\n"
			+ "      background-color: #ffffff;\r\n"
			+ "      padding: 20px;\r\n"
			+ "      border-radius: 8px;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    .email-header {\r\n"
			+ "      text-align: center;\r\n"
			+ "      background-color: #588157;\r\n"
			+ "      padding: 20px;\r\n"
			+ "      color: white;\r\n"
			+ "      border-radius: 8px 8px 0 0;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    .email-content {\r\n"
			+ "      padding: 20px;\r\n"
			+ "      color: #333;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    .email-content h2 {\r\n"
			+ "      color: #3a5a40;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    .banner-img {\r\n"
			+ "      width: 100%;\r\n"
			+ "      border-radius: 10px;\r\n"
			+ "      margin: 15px 0;\r\n"
			+ "    }\r\n"
			+ "\r\n"
			+ "    .email-footer {\r\n"
			+ "      font-size: 12px;\r\n"
			+ "      color: #777;\r\n"
			+ "      text-align: center;\r\n"
			+ "      padding: 10px;\r\n"
			+ "      border-top: 1px solid #ddd;\r\n"
			+ "    }\r\n"
			+ "  </style>\r\n"
			+ "</head>\r\n"
			+ "<body>\r\n"
			+ "  <div class=\"email-container\">\r\n"
			+ "    <header class=\"email-header\">\r\n"
			+ "      <h1>Sanvent Clínica Veterinaria</h1>\r\n"
			+ "    </header>\r\n"
			+ "\r\n"
			+ "    <div class=\"email-content\">\r\n"
			+ "      <h2>✨ Novedades del mes</h2>\r\n"
			+ "      <img src=\"https://i.postimg.cc/50Bk1KqK/asistente-en-veterinario.png\" alt=\"Imagen de novedades\" class=\"banner-img\" />\r\n"
			+ "      <p>\r\n"
			+ "        ¡Hola! En Sanvent nos encanta cuidar de tus mascotas. Este mes te traemos descuentos en vacunas,\r\n"
			+ "        nuevos servicios de peluquería y tips de salud animal. 🐶🐱\r\n"
			+ "      </p>\r\n"
			+ "      <p>\r\n"
			+ "        Visítanos o agenda tu cita en línea. ¡Tu mascota te lo agradecerá!\r\n"
			+ "      </p>\r\n"
			+ "    </div>\r\n"
			+ "\r\n"
			+ "    <footer class=\"email-footer\">\r\n"
			+ "      <p>📍 Calle Principal 123, Ciudad | ☎️ 123-456-789 | ✉️ contacto@sanvent.com</p>\r\n"
			+ "    </footer>\r\n"
			+ "  </div>\r\n"
			+ "</body>\r\n"
			+ "</html>";
}
